"use client";

export const stations = [
  {
    id: 1,
    title: "Neues + Altes Rathaus",
    riddle: "Wo residiert der Bürgermeister und wo tagte einst das Amtsgericht?",
    options: ["Passau", "Pfarrkirchen", "Simbach am Inn", "Eggenfelden"],
    correctAnswerIndex: 1,
    explanation:
      "Das Neue Rathaus ist der Sitz des Bürgermeisters. Im Alten Rathaus tagte früher das Amtsgericht.",
    mapUrl: "https://picsum.photos/400/300",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4371,
    longitude: 12.9388,
  },
  {
    id: 2,
    title: "Altstadt / Stadtmauer",
    riddle:
      "Wie viele Türme zählte die historische Stadtmauer einst, die heute noch teilweise sichtbar ist?",
    options: ["5", "7", "9", "11"],
    correctAnswerIndex: 2,
    explanation:
      "Die Stadtmauer hatte neun Türme, von denen einige noch heute stehen.",
    mapUrl: "https://picsum.photos/400/301",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4363,
    longitude: 12.9391,
  },
  {
    id: 3,
    title: "Alte Rennbahn",
    riddle: "Welches sportliche Ereignis fand hier regelmäßig statt, bevor das Gelände umgestaltet wurde?",
    options: ["Pferderennen", "Hunderennen", "Radrennen", "Bobbycar-Rennen"],
    correctAnswerIndex: 0,
    explanation:
      "Auf der Alten Rennbahn wurden früher Pferderennen veranstaltet.",
    mapUrl: "https://picsum.photos/400/302",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4415,
    longitude: 12.9448,
  },
  {
    id: 4,
    title: "Heilig-Geist-Spital",
    riddle: "Welchen Zweck erfüllte das Heilig-Geist-Spital ursprünglich?",
    options: [
      "Militärkrankenhaus",
      "Pilgerherberge",
      "Altersheim und Spital",
      "Ausbildungsstätte",
    ],
    correctAnswerIndex: 2,
    explanation:
      "Das Heilig-Geist-Spital diente als Altersheim und Spital für Bedürftige.",
    mapUrl: "https://picsum.photos/400/303",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4354,
    longitude: 12.9374,
  },
  {
    id: 5,
    title: "Stadtpfarrkirche",
    riddle:
      "Welchem Heiligen ist die Stadtpfarrkirche geweiht, deren barocke Gestaltung beeindruckt?",
    options: ["St. Stephan", "St. Nikolaus", "St. Martin", "St. Peter"],
    correctAnswerIndex: 0,
    explanation:
      "Die Stadtpfarrkirche ist dem Heiligen Stephan geweiht.",
    mapUrl: "https://picsum.photos/400/304",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4365,
    longitude: 12.9381,
  },
  {
    id: 6,
    title: "Gartlberg Kirche",
    riddle: "Für welche architektonische Besonderheit ist der Gartlberg bekannt?",
    options: [
      "Seine Größe",
      "Sein romanischer Stil",
      "Seine sechs Kapellen",
      "Sein hölzernes Dach",
    ],
    correctAnswerIndex: 2,
    explanation: "Der Gartlberg ist bekannt für seine sechs Kapellen.",
    mapUrl: "https://picsum.photos/400/305",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4314,
    longitude: 12.9354,
  },
  {
    id: 7,
    title: "Wimmer-Ross",
    riddle: "Wer schuf die Wimmer-Ross Skulptur?",
    options: [
      "Ein unbekannter Künstler",
      "Prof. Wimmer",
      "Ein italienischer Künstler",
      "Joseph von Kopf",
    ],
    correctAnswerIndex: 1,
    explanation: "Die Wimmer-Ross Skulptur wurde von Prof. Wimmer geschaffen.",
    mapUrl: "https://picsum.photos/400/306",
    googleMapsLink: "https://maps.app.goo.gl/...",
    latitude: 48.4374,
    longitude: 12.9394,
  },
];
